# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adki/work/seminars/202007_KAIST_NCL/session_03_clock/codes/ex_mmcm_ip/mmcm/vivado.z7/x/clk_wizard/clk_wizard.xci
# IP: The module: 'clk_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adki/work/seminars/202007_KAIST_NCL/session_03_clock/codes/ex_mmcm_ip/mmcm/vivado.z7/x/clk_wizard/clk_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/adki/work/seminars/202007_KAIST_NCL/session_03_clock/codes/ex_mmcm_ip/mmcm/vivado.z7/x/clk_wizard/clk_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/adki/work/seminars/202007_KAIST_NCL/session_03_clock/codes/ex_mmcm_ip/mmcm/vivado.z7/x/clk_wizard/clk_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/adki/work/seminars/202007_KAIST_NCL/session_03_clock/codes/ex_mmcm_ip/mmcm/vivado.z7/x/clk_wizard/clk_wizard.xci
# IP: The module: 'clk_wizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adki/work/seminars/202007_KAIST_NCL/session_03_clock/codes/ex_mmcm_ip/mmcm/vivado.z7/x/clk_wizard/clk_wizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/adki/work/seminars/202007_KAIST_NCL/session_03_clock/codes/ex_mmcm_ip/mmcm/vivado.z7/x/clk_wizard/clk_wizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/adki/work/seminars/202007_KAIST_NCL/session_03_clock/codes/ex_mmcm_ip/mmcm/vivado.z7/x/clk_wizard/clk_wizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
